version: '3.3'

services:
  csvloader:
    build: ./
    command: ./wait-for-postgres.sh db ./CsvLoader
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./.build/volumes/logs:/logs


  db:
    restart: always
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  pgdata: